### ISSUE TITLE
Find first uid on various linux distributions

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/default-uid#1]
From [wikipedia](https://en.wikipedia.org/wiki/User_identifier):

> Some POSIX systems allocate UIDs for new users starting from 500 (OS X, Red Hat Enterprise Linux), others start at 1000 (openSUSE, Debian[5]). On many Linux systems, these ranges are specified in /etc/login.defs, for useradd and similar tools.

I think an approach would be:

1) read `/etc/login.defs`, return UID_MIN if found. Here's the relevant section from Arch Linux:

```
#
# Min/max values for automatic uid selection in useradd
#
UID_MIN                  1000
UID_MAX                 60000
```

2) if there's no uid from step 1, try to detect distribution, maybe through `lsb_release` or similar, and fall back to a hardcoded list of uids for distributions.

**Comment by silverwind** [comment]
Or, a even better approach could be to somehow detect the first user in the regular user range that actually _exists_. That's probably better than just blindly taking the first uid in the range.

**Comment by sindresorhus** [comment]
> Some POSIX systems allocate UIDs for new users starting from 500 (OS X, Red Hat Enterprise Linux), others start at 1000 (openSUSE, Debian[5]). On many Linux systems, these ranges are specified in /etc/login.defs, for useradd and similar tools.

Do they actually still do this though? That might be outdated info.

**Comment by sindresorhus** [comment]
> Or, a even better approach could be to somehow detect the first user in the regular user range that actually exists. That's probably better than just blindly taking the first uid in the range.

:+1: If possible, then yeah.

**Comment by silverwind** [comment]
> Do they actually still do this though? That might be outdated info.

Will test on RedHat later. OS X confirms this quote too, it's just strange they took `501` for the first user instead of `500`. Probably an pretty historic mistake :laughing:.

**Comment by silverwind** [comment]
Just dumping some information.

For distribution detection, we probably want to use [getos](https://github.com/wblankenship/getos).Here's a list of UID_MINs based on the Information I've found so far:
- RedHat: 500
- CentOS: 500
- Fedora < 15: 500
- Fedora >= 16: 1000 [ref](https://lists.stg.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/IFDNSLG7LSQOHIIJ6VTS4I63TQNL3RJU/)
- Every other distro: 1000

**Comment by silverwind** [comment]
Detection on OS X could be done by parsing the output of `dscacheutil`:

```
dscacheutil -q user | grep -A 3 -B 2 -e 'uid:\ 50[0-9]'
```

**Comment by silverwind** [comment]
As noted in #2, detection is probably better done in its own module.
